
name: Deploy CD

on:
  workflow_run:
    workflows: ["Build CI"]
    types: [completed]
    branches:
      - 'develop'
      - 'master'

jobs:
    deploy:
      runs-on: ubuntu-latest
      
      steps:
      - uses: devtomio/action-railway@v1.1.4
      - name: Deploy to Railway
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
