
name: Deploy CD

on:
  workflow_run:
    workflows: ["Build CI"]
    types: [completed]
    branches:
      - 'develop'
      - 'master'

jobs:
    deploy:
      runs-on: ubuntu-latest
      
      steps:
       - name: Install Railway
         run: npm i -g @railway/cli
         
       - name: Deploy
         run: railway up
         env:
           RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
