
name: Deploy CD

on:
  workflow_run:
    workflows: ["Build CI"]
    types: [completed]
    branches:
      - 'develop'
      - 'master'

jobs:
  deploy:
    - name: Deploy to Railway
      uses: devtomio/action-railway@v1.1.4
      with:
        railway_token: {{ secrets.RAILWAY_TOKEN }}
